export const FETCH_YOUTUBE = 'FETCH_YOUTUBE';
export const FETCH_SEARCH = 'FETCH_SEARCH';
export const FETCH_PLAYLIST = 'FETCH_PLAYLIST';
export const SAVE_YOUTUBE = 'SAVE_YOUTUBE';
export const SAVE_PLAYLIST = 'SAVE_PLAYLIST';
export const SET_LOADING = 'SET_LOADING';
export const SET_ACTIVE_PLAYLIST = 'SET_ACTIVE_PLAYLIST';

export const SET_PLAYER_SCREEN = "SET_PLAYER_SCREEN"
